from pathlib import Path
import sys
ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path: sys.path.insert(0, str(ROOT_DIR))
import argparse, uuid
from PIL import Image
from scripts.common import write_json, append_jsonl, sha256_file, sha256_text, utc_now, list_frames, read_json

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("session"); ap.add_argument("--title", default="ARC-StreamMemory Session"); ap.add_argument("--summary", default="Visual memory session generated by ARC-StreamMemory."); args=ap.parse_args()
    session=Path(args.session); frames=list_frames(session)
    if not frames: raise SystemExit("No frames found")
    session_id="stream_"+uuid.uuid5(uuid.NAMESPACE_URL,str(session.resolve())).hex[:16]
    policy_path=session/"memory"/"capture_policy.json"; policy=read_json(policy_path) if policy_path.exists() else {"capture_mode":"unknown","ai_frame_rate":1}
    fps=policy.get("ai_frame_rate") or 1
    entries=[]
    for idx,frame in enumerate(frames,1):
        with Image.open(frame) as im: w,h=im.size
        entries.append({"frame_id":f"frame_{idx:06d}","path":str(frame.relative_to(session)),"index":idx,"timestamp_ms":int((idx-1)*1000/fps),"width":w,"height":h,"sha256":sha256_file(frame)})
    write_json(session/"memory"/"frame_index.json", {"schema":"arc.streammemory.frame_index.v2","session_id":session_id,"title":args.title,"created_at":utc_now(),"frame_count":len(entries),"frames":entries})
    (session/"memory"/"session_summary.md").write_text(f"# {args.title}\n\n{args.summary}\n\nFrames: {len(entries)}\n", encoding="utf-8")
    timeline=session/"memory"/"event_timeline.jsonl"; timeline.parent.mkdir(parents=True, exist_ok=True); timeline.write_text("", encoding="utf-8")
    for e in entries:
        if e["index"] in (1,len(entries)) or e["index"] % max(1,len(entries)//4)==0:
            append_jsonl(timeline,{"event_id":f"event_{e['index']:06d}","time_ms":e["timestamp_ms"],"type":"frame_checkpoint","summary":f"Visual checkpoint at {e['frame_id']}","frame_ref":e["frame_id"],"frame_hash":e["sha256"]})
    (session/"memory"/"ocr_index.jsonl").write_text("", encoding="utf-8")
    receipts=session/"receipts"/"arc_receipts.jsonl"; receipts.parent.mkdir(parents=True, exist_ok=True); receipts.write_text("", encoding="utf-8")
    append_jsonl(receipts,{"receipt_type":"arc.streammemory.session.created","session_id":session_id,"title":args.title,"created_at":utc_now(),"frame_count":len(entries),"capture_mode":policy.get("capture_mode")})
    for e in entries: append_jsonl(receipts,{"receipt_type":"arc.streammemory.frame.indexed","session_id":session_id,"frame_id":e["frame_id"],"frame_hash":e["sha256"],"timestamp_ms":e["timestamp_ms"]})
    chunks=[]
    for ci in range(0,len(entries),16):
        group=entries[ci:ci+16]
        chunks.append({"chunk_id":f"chunk_{ci//16+1:06d}","spine_pointer":f"ob://visual/{session_id}/chunk_{ci//16+1:06d}","frame_refs":[x["frame_id"] for x in group],"start_ms":group[0]["timestamp_ms"],"end_ms":group[-1]["timestamp_ms"],"hash":sha256_text("".join(x["sha256"] for x in group))})
    write_json(session/"omnibinary"/"chunk_map.json", {"schema":"arc.streammemory.omnibinary_chunk_map.v2","session_id":session_id,"chunks":chunks})
    write_json(session/"arcrar"/"bundle_manifest.json", {"schema":"arc.streammemory.arcrar_bundle_manifest.v2","session_id":session_id,"title":args.title,"created_at":utc_now(),"contains":["frames/","memory/","receipts/","omnibinary/","arcrar/"]})
    write_json(session/"memory"/"module_attachment.json", {"schema":"arc.visual_memory.module_attachment.v2","module_attachment_type":"arc.visual_memory","session_id":session_id,"title":args.title,"summary":args.summary,"created_at":utc_now(),"capture_policy":policy,"frame_index":"memory/frame_index.json","event_timeline":"memory/event_timeline.jsonl","ocr_index":"memory/ocr_index.jsonl","ai_digest_md":"memory/ai_digest.md","ai_digest_json":"memory/ai_digest.json","summary_md":"memory/session_summary.md","receipts":"receipts/arc_receipts.jsonl","omnibinary_chunk_map":"omnibinary/chunk_map.json","arcrar_bundle_manifest":"arcrar/bundle_manifest.json","memory_spine":"memory/memory_spine.json","seed_spine":"memory/seed_spine.json","permissions":{"recorded_by_user":True,"local_only_default":True,"shareable":False}})
    print(f"Built stream memory: {session_id}")
if __name__=="__main__": main()
