from pathlib import Path
import sys, argparse, uuid
ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path: sys.path.insert(0, str(ROOT_DIR))
from PIL import Image
from scripts.common import write_json, append_jsonl, sha256_file, sha256_text, utc_now, list_frames, read_json

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('session')
    ap.add_argument('--title', default='ARC-StreamMemory Session')
    ap.add_argument('--summary', default='Visual memory session generated by ARC-StreamMemory.')
    args = ap.parse_args()
    session = Path(args.session)
    frames = list_frames(session)
    if not frames: raise SystemExit('No frames found.')
    session_id = 'stream_' + uuid.uuid5(uuid.NAMESPACE_URL, str(session.resolve())).hex[:16]
    policy = read_json(session / 'memory' / 'capture_policy.json')
    fps = policy.get('ai_frame_rate') or 1
    entries = []
    for idx, frame in enumerate(frames, 1):
        with Image.open(frame) as im: w, h = im.size
        entries.append({'frame_id': f'frame_{idx:06d}', 'path': str(frame.relative_to(session)), 'index': idx, 'timestamp_ms': int((idx-1)*1000/fps), 'width': w, 'height': h, 'sha256': sha256_file(frame)})
    write_json(session/'memory'/'frame_index.json', {'schema':'arc.streammemory.frame_index.v1','session_id':session_id,'title':args.title,'created_at':utc_now(),'frame_count':len(entries),'frames':entries})
    (session/'memory'/'session_summary.md').write_text(f'# {args.title}\n\n{args.summary}\n\nFrames: {len(entries)}\n', encoding='utf-8')
    timeline = session/'memory'/'event_timeline.jsonl'
    if timeline.exists(): timeline.unlink()
    for e in entries:
        if e['index'] in (1, len(entries)) or e['index'] % max(1, len(entries)//4) == 0:
            append_jsonl(timeline, {'event_id': f"event_{e['index']:06d}", 'time_ms': e['timestamp_ms'], 'type':'frame_checkpoint', 'summary': f"Visual checkpoint at {e['frame_id']}", 'frame_ref': e['frame_id'], 'frame_hash': e['sha256']})
    receipts = session/'receipts'/'arc_receipts.jsonl'
    if receipts.exists(): receipts.unlink()
    append_jsonl(receipts, {'receipt_type':'arc.streammemory.session.created','session_id':session_id,'title':args.title,'created_at':utc_now(),'frame_count':len(entries)})
    for e in entries:
        append_jsonl(receipts, {'receipt_type':'arc.streammemory.frame.indexed','session_id':session_id,'frame_id':e['frame_id'],'frame_hash':e['sha256'],'timestamp_ms':e['timestamp_ms']})
    chunks=[]
    for ci in range(0,len(entries),16):
        group=entries[ci:ci+16]
        chunks.append({'chunk_id':f'chunk_{ci//16+1:06d}','spine_pointer':f'ob://visual/{session_id}/chunk_{ci//16+1:06d}','frame_refs':[e['frame_id'] for e in group],'hash':sha256_text(''.join(e['sha256'] for e in group))})
    write_json(session/'omnibinary'/'chunk_map.json', {'schema':'arc.streammemory.omnibinary_chunk_map.v1','session_id':session_id,'chunks':chunks})
    write_json(session/'arcrar'/'bundle_manifest.json', {'schema':'arc.streammemory.arcrar_bundle_manifest.v1','session_id':session_id,'title':args.title,'created_at':utc_now(),'contains':['frames/','memory/','receipts/','omnibinary/','arcrar/']})
    write_json(session/'memory'/'module_attachment.json', {'schema':'arc.visual_memory.module_attachment.v1','module_attachment_type':'arc.visual_memory','session_id':session_id,'title':args.title,'summary':args.summary,'created_at':utc_now(),'capture_policy':policy,'frame_index':'memory/frame_index.json','event_timeline':'memory/event_timeline.jsonl','summary_md':'memory/session_summary.md','receipts':'receipts/arc_receipts.jsonl','omnibinary_chunk_map':'omnibinary/chunk_map.json','arcrar_bundle_manifest':'arcrar/bundle_manifest.json','permissions':{'recorded_by_user':True,'local_only_default':True,'shareable':False}})
    print(f'Built stream memory: {session_id}')
if __name__ == '__main__': main()
